---
prompt-install: false
dont-chroot: false
oem-setup: false

disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false

#modules-search-path:
#  - /usr/lib/calamares/modules

modules-search: [ local ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary

  - exec:
      - partition
      - mount
      - unpackfs
      - locale
      - keyboard
      - users
      - akspa-user-config
      - bootloader

  - show:
      - finished

branding: akspa

